### ISSUE TITLE
Data link availability

### ISSUE THREAD

**Issue by joegeorgeson** [adbailey4/yeast_rrna_modification_detection#1]
Hi devs,

I get the below errors when trying to download using aspera and wget - can you let me know if the links are public yet? ...or if this is an issue on my end?

aspera example;
```
$ ~/bin/ascp -QT -l 300m -P33001 -i ~/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:vol1/run/ERR716/ERR7162387/20190610_R941_CBF5GAL.tar.gz .

ascp: Failed to open TCP connection for SSH, exiting.

Session Stop  (Error: Failed to open TCP connection for SSH)
```

wget example;
```
 $ wget https://sra-download.ncbi.nlm.nih.gov/traces/sra69/SRZ/016584/SRR16584067/20210415_R941_mutant451.fastq.gz
--2021-12-19 18:02:45--  https://sra-download.ncbi.nlm.nih.gov/traces/sra69/SRZ/016584/SRR16584067/20210415_R941_mutant451.fastq.gz
Resolving sra-download.ncbi.nlm.nih.gov (sra-download.ncbi.nlm.nih.gov)... 165.112.9.235, 130.14.250.24, 130.14.250.25
Connecting to sra-download.ncbi.nlm.nih.gov (sra-download.ncbi.nlm.nih.gov)|165.112.9.235|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-19 18:02:46 ERROR 404: Not Found
```

Thanks!
Joe

**Comment by adbailey4** [comment]
1) For the fastq's, I am working with SRA to get the raw reads public so for right now those are not going to be accessible for a bit. You got to SRA and download the de-identified fastq's but you need the raw files to run our pipeline. If you don't want to wait, just basecall the fast5's with guppy.

2) Can you confirm that the asperaweb_id_dsa.openssh is in fact `~/etc/asperaweb_id_dsa.openssh`. I think your problem is a connection issue, not a data availability issue.

3) To confirm the data is there, try `wget ftp.sra.ebi.ac.uk/vol1/run/ERR716/ERR7162387/20190610_R941_CBF5GAL.tar.gz`. If this works, then you have not configured aspera correctly. I have a gist to install aspera [here](https://gist.github.com/adbailey4/237d0ca229f5e3c8033933a50a143348)

**Comment by joegeorgeson** [comment]
The `wget ftp.sra.ebi.ac.uk/vol1/run/ERR716/ERR7162387/20190610_R941_CBF5GAL.tar.gz` works so I'm guessing the aspera issue is something security related (I know aspera works, and I'm working my institute's cluster where security issues are common...will write sysadm/devops). Thanks for the help!

**Comment by adbailey4** [comment]
No problem! Once there is easy public access to fastq files I will close this issue.

**Comment by adbailey4** [comment]
#2 Fastq data is now hosted on ENA
* Pulled in updates to the minor example with a working fastq.gz download link. 
* Updated end_to_end.md documentation to download fastq files from ENA.
